/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

/**
 *
 * @author kcorr
 */
public class Comentario extends javax.swing.JPanel {

    /**
     * Creates new form Comentario
     */
    public Comentario(String name,String description) {
        initComponents();
        this.lblName.setText(name);
        this.txtComment.setText(description);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        txtNombre = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lblName.setText("Nombre");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 380, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtComment.setColumns(20);
        txtComment.setLineWrap(true);
        txtComment.setRows(5);
        txtComment.setToolTipText("");
        txtComment.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtComment);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 440, 50));

        txtNombre.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtNombre.setText("Nombre");
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
