/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

/**
 *
 * @author kcorr
 */
public class Reviews extends javax.swing.JPanel {

    /**
     * Creates new form Reviews
     */
    public Reviews(String name,String Stars,String description) {
        initComponents();
        this.lblOwner.setText(name);
        this.lblStars.setText(Stars);
        this.txtComment.setText(description);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOwner = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lblEventName1 = new javax.swing.JLabel();
        lblStars = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 200));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOwner.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        lblOwner.setForeground(new java.awt.Color(255, 255, 255));
        lblOwner.setText("Nombre del Evento");
        jPanel1.add(lblOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 270, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtComment.setEditable(false);
        txtComment.setBackground(new java.awt.Color(40, 40, 40));
        txtComment.setColumns(20);
        txtComment.setForeground(new java.awt.Color(255, 255, 255));
        txtComment.setRows(5);
        txtComment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtComment);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 580, 100));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblEventName1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        lblEventName1.setForeground(new java.awt.Color(255, 255, 255));
        lblEventName1.setText("Estrellas");
        jPanel1.add(lblEventName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 270, -1));

        lblStars.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        lblStars.setForeground(new java.awt.Color(255, 255, 255));
        lblStars.setText("1");
        jPanel1.add(lblStars, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEventName1;
    private javax.swing.JLabel lblOwner;
    private javax.swing.JLabel lblStars;
    private javax.swing.JTextArea txtComment;
    // End of variables declaration//GEN-END:variables
}
