/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Business.Funcion;
import Business.Person;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.util.Rotation;


/**
 *
 * @author kcorr
 */
public class Statistics extends javax.swing.JFrame {

    /**
     * Creates new form Statistics
     */
    public Statistics(Person person) {
        initComponents();
        ocultarCajas();
        setPerson(person);
                if(person.getTypeUser()!=1){  //significa que  no es administrador
            this.btnNuevoEvento.setVisible(false);
            this.btnEstadisticas.setVisible(false);
        }
    }
    
    public void ocultarCajas(){
        this.lblSeleccione.setVisible(false);
        this.lblFecha.setVisible(false);
        this.lblTop.setVisible(false);
        //this.lblClasificacion.setVisible(false);
        this.txtFecha.setVisible(false);
        //this.jCategoria.setVisible(false);
        this.jTop.setVisible(false);   
    }

    private Statistics() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    private Person person; 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();
        panelGrafica = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTop = new javax.swing.JLabel();
        jFiltro = new javax.swing.JComboBox<>();
        jTop = new javax.swing.JTextField();
        lblSeleccione = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnEstadisticas = new javax.swing.JLabel();
        btnNuevoEvento = new javax.swing.JLabel();
        btnConfig = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnConsultas = new javax.swing.JLabel();
        btnCalificar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Consultar");
        jButton2.setActionCommand("");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        txtFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 30));

        panelGrafica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelGrafica.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 170, 290));

        jPanel1.add(panelGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 380));

        lblTop.setText("Top");
        jPanel1.add(lblTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 60, 30));

        jFiltro.setBackground(new java.awt.Color(40, 40, 40));
        jFiltro.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jFiltro.setForeground(new java.awt.Color(255, 255, 255));
        jFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Categoría", "Eventos Por Fecha", "Top Eventos por Asistencia", "Top Eventos mejor Calificación", "Top Eventos peor Calificación", "Rango de Edad Usuarios", "Reseñas por Categoría", " ", " " }));
        jFiltro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jFiltroItemStateChanged(evt);
            }
        });
        jPanel1.add(jFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, 30));

        jTop.setBackground(new java.awt.Color(40, 40, 40));
        jTop.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jTop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTopActionPerformed(evt);
            }
        });
        jPanel1.add(jTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 50, 30));

        lblSeleccione.setText("Seleccione el dato requerido para aplicar ek filtro");
        jPanel1.add(lblSeleccione, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel3.setText("Filtrar por");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 30));

        lblFecha.setText("Fecha");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 60, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 670, 600));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(130, 600));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/combo_chart_64px.png"))); // NOI18N
        btnEstadisticas.setToolTipText("Estadisticas");
        btnEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstadisticasMouseClicked(evt);
            }
        });
        jPanel4.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        btnNuevoEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new_64px.png"))); // NOI18N
        btnNuevoEvento.setToolTipText("Nuevo");
        btnNuevoEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoEventoMouseClicked(evt);
            }
        });
        jPanel4.add(btnNuevoEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings_3_64px.png"))); // NOI18N
        btnConfig.setToolTipText("Configuración");
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
        });
        jPanel4.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_64px.png"))); // NOI18N
        btnHome.setToolTipText("Inicio");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        jPanel4.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question_shield_64px.png"))); // NOI18N
        btnConsultas.setToolTipText("Consultas");
        btnConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultasMouseClicked(evt);
            }
        });
        jPanel4.add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnCalificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rating_64px.png"))); // NOI18N
        btnCalificar.setToolTipText("Calificar Eventos");
        btnCalificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalificarMouseClicked(evt);
            }
        });
        jPanel4.add(btnCalificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadisticasMouseClicked
        this.dispose();
        Statistics ventana = new Statistics(getPerson());
        ventana.setVisible(true);
    }//GEN-LAST:event_btnEstadisticasMouseClicked

    private void btnNuevoEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoEventoMouseClicked
        try {
            this.dispose();
            NuevoEvento ventana = new NuevoEvento(getPerson());
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoEventoMouseClicked

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfigMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        try {
            this.dispose();
            EventViewer ventana = new EventViewer(getPerson());
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasMouseClicked
        this.dispose();
        Consultas ventana = new Consultas(getPerson());
        ventana.setVisible(true);
    }//GEN-LAST:event_btnConsultasMouseClicked

    private void btnCalificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalificarMouseClicked
        try {
            this.dispose();
            CountingStars ventana = new CountingStars(getPerson());
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCalificarMouseClicked

    private void jTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTopActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            DefaultPieDataset result =new DefaultPieDataset();
            Funcion functions=new Funcion();
            ResultSet rs=null;
            String opc = jFiltro.getSelectedItem().toString();
            int topValue;
            switch (opc){
                case "Por Categoría":
                    rs=functions.statisticsEventXClassification();//aqui va la funcion del connect
                    while(rs.next()){
                        try {
                            result.setValue(rs.getString("CLASSIFICATION_NAME"),Integer.parseInt((rs.getString("PARCIAL"))));
                        } catch (SQLException ex) {
                            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    // se modifica el result para que muestre los datos de la siguiente manera:
                    //result.setValue("jaja",55);
                    crearPieChart(result);
                    break;
                case "Eventos Por Fecha":
                    /*rs=functions.statisticsEventXClassification();//aqui va la funcion del connect
                    while(rs.next()){
                        try {
                            result.setValue(rs.getString("CLASSIFICATION_NAME"),Integer.parseInt((rs.getString("PARCIAL"))));
                        } catch (SQLException ex) {
                            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    */
                    crearPieChart(result);
                    break;
                case "Top Eventos por Asistencia":
                    topValue= Integer.parseInt(jTop.getText());
                    rs=functions.statisticsTopMoreAttendees(topValue);//aqui va la funcion del connect
                    while(rs.next()){
                        try {
                            result.setValue(rs.getString("EVENT_NAME"),Integer.parseInt((rs.getString("ASSISTANCE"))));
                        } catch (SQLException ex) {
                            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    crearPieChart(result);
                    break;
                case "Top Eventos mejor Calificación":
                    topValue = Integer.parseInt(jTop.getText());
                    rs=functions.statisticsTopBestReview(topValue);//aqui va la funcion del connect
                    while(rs.next()){
                        try {
                            result.setValue(rs.getString("EVENT_NAME"),Integer.parseInt((rs.getString("REVIEW"))));
                        } catch (SQLException ex) {
                            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    crearPieChart(result);
                    break;
                case"Top Eventos peor Calificación":
                    topValue = Integer.parseInt(jTop.getText());
                    rs=functions.statisticsTopWorstReview(topValue);//aqui va la funcion del connect
                    while(rs.next()){
                        try {
                            result.setValue(rs.getString("EVENT_NAME"),Integer.parseInt((rs.getString("REVIEW"))));
                        } catch (SQLException ex) {
                            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    crearPieChart(result);
                    break;
                    
                case "Rango de Edad Usuarios":
                    rs=functions.statisticsAgeRange();//aqui va la funcion del connect
                    while(rs.next()){
                        try {
                            result.setValue(rs.getString("AGE"),Integer.parseInt((rs.getString("PARCIAL"))));
                        } catch (SQLException ex) {
                            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    crearPieChart(result);
            
                    break;
                case "Reseñas por Categoría":
                    rs=functions.statisticsReviewXClassification();//aqui va la funcion del connect
                    while(rs.next()){
                        try {
                            result.setValue(rs.getString("CLASSIFICATION_NAME"),Integer.parseInt((rs.getString("PARCIAL"))));
                        } catch (SQLException ex) {
                            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    crearPieChart(result);
                    break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jFiltroItemStateChanged
        ocultarCajas();
        this.lblSeleccione.setVisible(true);
        if(jFiltro.getSelectedIndex()==2 || jFiltro.getSelectedIndex()==3 || jFiltro.getSelectedIndex()==4){
            this.lblTop.setVisible(true);
            this.jTop.setVisible(true);
        }
    }//GEN-LAST:event_jFiltroItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }
    
    
        public void crearPieChart(DefaultPieDataset data){
        
        panelGrafica.removeAll();
        panelGrafica.repaint();
        //DefaultPieDataset result =new DefaultPieDataset();
        //result.setValue("hola", 22);
        //result.setValue("jaja",55);
        
        JFreeChart chart =ChartFactory.createPieChart3D("", data, true,true,false);
        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(0);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        plot.setSimpleLabels(true);
        
        PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
            "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
        plot.setLabelGenerator(gen);
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(600,400));
        chartPanel.setBackground(new Color(0,0,0,80));

        panelGrafica.add(chartPanel,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 380));
        pack();
    }
        
        
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCalificar;
    private javax.swing.JLabel btnConfig;
    private javax.swing.JLabel btnConsultas;
    private javax.swing.JLabel btnEstadisticas;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnNuevoEvento;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jFiltro;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTop;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblSeleccione;
    private javax.swing.JLabel lblTop;
    private javax.swing.JPanel panelGrafica;
    private com.toedter.calendar.JDateChooser txtFecha;
    // End of variables declaration//GEN-END:variables
}
